def bucketname = null
pipeline{
    agent any
    tools {
        terraform 'terraform-11'
    }
    parameters {
      string description: 'Name of the S3 Bucket', name: 'bucketName'
      string description: 'OPS Ticket Number Eg: OPS-11913', name: 'ticket_number'
      string description: 'Variable file name (without .tfvars extension)', name: 'file_name'
}

    // }
    stages {
//         stage('Git checkout')
//         {
            
//                 steps{
//                     git branch: 'main', credentialsId: '02c515b6-f2d9-433b-914c-a18921a5dad1', url: 'https://github.com/AdityaNutulapati/test-s3-1'
                    
//                 }
//         }
        // stage('Input Bucket Name')
        // {
        //     steps{
        //         script {
        //     bucketName = input (
        //     message: 'Enter Name of the Bucket', 
        //     ok: 'Submit', 
        //     parameters: [string(name: 'bucketName', trim: true)]
        //   )
        // }
            // }
        // }
        stage('Terraform Init')
        {
            steps{
                sh "echo 'QA/S3/'$ticket_number'-'$file_name"
                sh "cd 'QA/S3/'$ticket_number'-'$file_name"
                sh "ls"
                sh "pwd"
                sh "terraform -chdir='QA/S3/'$ticket_number'-'$file_name init"
                // sh "pwd"
                
            }
        }
        stage('Terraform Plan')
        {
            steps{
                withCredentials([[
                    $class:'AmazonWebServicesCredentialsBinding',
                    credentialsId:'aws-credentials',
                    accessKeyVariable:'AWS_ACCESS_KEY_ID',
                    secretKeyVariable:'AWS_SECRET_ACCESS_KEY']])
                    {
                        // sh "TEST=`pwd`"
                        sh "terraform -chdir='QA/S3/'$ticket_number'-'$file_name plan -var-file `pwd`'QA/S3/Variables/'$file_name'.tfvars'"
                    }
            }
        }
    
        // -var="bucketname=adityas3"
        stage('Terraform Apply')
        {
            steps{
            withCredentials([[
                    $class:'AmazonWebServicesCredentialsBinding',
                    credentialsId:'aws-credentials',
                    accessKeyVariable:'AWS_ACCESS_KEY_ID',
                    secretKeyVariable:'AWS_SECRET_ACCESS_KEY']])
                    {
                        sh "terraform -chdir=s3 apply -var 'bucketname=$bucketName' -var 'ticket_number=$ticket_number' --auto-approve"
                    }
            }
        }
    }
}
// }
